# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Sam\Dropbox\Work\2014\PSoC 4 Modbus Slave Software\PSoC 4 Pioneer Modbus Slave\PSoC 4 Pioneer Modbus Slave.cydsn\PSoC 4 Pioneer Modbus Slave.cyprj
# Date: Mon, 17 Mar 2014 12:12:46 GMT
#set_units -time ns
create_clock -name {MessageTimerClock(FFB)} -period 2000 -waveform {0 1000} [list [get_pins {ClockBlock/ff_div_8}]]
create_clock -name {ModbusUART_SCBCLK(FFB)} -period 6500 -waveform {0 3250} [list [get_pins {ClockBlock/ff_div_2}]]
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_generated_clock -name {MessageTimerClock} -source [get_pins {ClockBlock/hfclk}] -edges {1 49 97} [list]
create_generated_clock -name {ModbusUART_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 157 313} [list]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]


# Component constraints for C:\Users\Sam\Dropbox\Work\2014\PSoC 4 Modbus Slave Software\PSoC 4 Pioneer Modbus Slave\PSoC 4 Pioneer Modbus Slave.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Sam\Dropbox\Work\2014\PSoC 4 Modbus Slave Software\PSoC 4 Pioneer Modbus Slave\PSoC 4 Pioneer Modbus Slave.cydsn\PSoC 4 Pioneer Modbus Slave.cyprj
# Date: Mon, 17 Mar 2014 12:12:44 GMT
